spring:
  profiles:
    active: local # 여기서 어떤 환경을 쓸지 결정합니다.
  application:
    name: BuddySecret

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false