spring:
  profiles:
    active: local # 여기서 어떤 환경을 쓸지 결정합니다.
  application:
    name: BuddySecret

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) %clr(---){faint} %clr([%X{txId:-system}]){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    org.springframework.web: DEBUG
    io.bani: DEBUG